// <auto-generated />
using System;
using HomeWizardMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeWizardMonitor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("HomeWizardMonitor.Models.EnergyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActivePowerW")
                        .HasColumnType("REAL");

                    b.Property<double>("SelfConsumedSolarKwh")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalPowerExportKwh")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPowerImportKwh")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("EnergyData");
                });
#pragma warning restore 612, 618
        }
    }
}
